version: '3'
    
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - redis
    volumes:
      - ./:/app
    networks:
      - mynetwork

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    tmpfs:
      - /data
    ports:
      - 6379:6379
    networks:
      - mynetwork

volumes:
  redis_data:
    external: false
networks:
  mynetwork: